---

syslog_logs:
  ansible:
    file_name: ansible.log
    filter:
      filter: program(ansible)
  remote:
    source: net
    template: nginx
    file_name: "remote/nginx/${HOST}/${YEAR}.${MONTH}.${DAY}/messages.log"
  remote_foo:
    source: net
    file_name: "remote/${HOST}/message"
    filter:
      filter:
        - not host("localhost")
  separatedbyhosts:
    source: s_remote
    file_name: "remote/$HOST/$YEAR-$MONTH-$DAY/messages"
    flags:
      - fallback

syslog_sources:
  net:
    - comment: network
      udp:

  s_remote:
    - comment: remote sources on port 5140
      tcp:
        ip: 10.19.0.10
        port: 5140

  source_6514_tls:
    - comment: "see https://github.com/bodsch/ansible-syslog-ng/pull/13#issuecomment-1584094073"
      network:
        # ip: 10.19.0.10
        port: 6514
        transport: tls
        max_connections: 300
        keep_alive: true
        tcp_keep_alive: true
        tls:
          key_file: /etc/ssl/molecule.local/molecule.local.key
          cert_file: /etc/ssl/molecule.local/molecule.local.pem
          # ca_dir: /etc/ssl/molecule.local
          peer_verify: required-trusted
          ssl-options:
            - no-sslv2
            - no-sslv3
            - no-tlsv1
