---

- name: check configuration  # noqa no-changed-when
  syslog_cmd:
    parameters:
      - --syntax-only
  register: syslog_validate_config

- name: enable and start syslog-ng (no systemd)
  service:
    name: syslog-ng
    enabled: true
    state: started
  when:
    - ansible_service_mgr != "systemd"

- block:
    - name: populate service facts
      service_facts:
      register: systemd_facts

    - name: set systemd unit name
      set_fact:
        syslog_unit_file: "{{ ansible_facts.services | get_service('syslog-ng') }}"

    - name: detect systemd template unit
      stat:
        path: /etc/default/{{ syslog_unit_file }}{{ syslog_systemd_template }}
      register: systemd_template
      when:
        - syslog_unit_file is match('.*@')

    - name: use systemd template unit
      block:
        - name: set link for template unit
          file:
            src: /lib/systemd/system/{{ syslog_unit_file }}.service
            dest: /etc/systemd/system/{{ syslog_unit_file }}{{ syslog_systemd_template }}.service
            state: link
          notify:
            - reload systemctl daemon

        - name: define systemd template unit
          set_fact:
            syslog_unit_file: "{{ syslog_unit_file }}{{ syslog_systemd_template }}"
      when:
        - syslog_unit_file is match('.*@')
        - systemd_template.stat.exists

    - name: enable {{ syslog_unit_file }}.service
      service:
        name: '{{ syslog_unit_file }}'
        enabled: true
      when:
        - syslog_unit_file is defined

    - name: start {{ syslog_unit_file }}.service
      service:
        name: '{{ syslog_unit_file }}'
        state: started
      register: service_status
      notify:
        - reload systemctl daemon
        - wait 20 seconds for clean startup
      when:
        - syslog_unit_file is defined

  when:
    - ansible_service_mgr == "systemd"
