---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: instance
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - syslog_ng
      - syslog_ng_server
    docker_networks:
      - name: syslog-ng
        ipam_config:
          - subnet: "10.17.0.0/24"
            gateway: "10.17.0.254"
    networks:
      - name: syslog-ng
        ipv4_address: "10.17.0.10"

  - name: client_1
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - syslog_ng
      - syslog_ng_client
    networks:
      - name: syslog-ng
        ipv4_address: "10.17.0.30"

  - name: client_2
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - syslog_ng
      - syslog_ng_client
    networks:
      - name: syslog-ng
        ipv4_address: "10.17.0.31"

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: True
      # callback_plugins: "${PWD}/molecule/server-clients/callbacks"
      stdout_callback: yaml
      # callback_plugins: anstomlog
      callbacks_enabled: profile_tasks

scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
